jekyll:
    image: jekyll/builder:3.8.2
    command: jekyll serve --watch --incremental --force-polling
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
        - ./vendor/bundle:/usr/local/bundle